// Generated by embed_scene.py from scene.html -- regenerate, don't edit.
// 678 bytes of drm_scene_ir.
#pragma once

static const char PANEL_SCENE[] = R"panel_scene({"version":1,"name":"scene","width":320,"height":480,"fit":"contain","duration":3000,"layers":[{"id":"bg","z":0,"objects":[{"type":"rect","id":"box0","x":0,"y":0,"w":320,"h":480,"fill":"#101014"}]},{"id":"label","z":10,"objects":[{"type":"rect","id":"box1","x":20,"y":180,"w":280,"h":64,"fill":"#1e2a3a"},{"type":"text","id":"text2","content":"drm_scene_ir","font_id":"montserrat-24","x":36,"y":198,"color":"#e8e8f0"}]},{"id":"ink","z":20,"objects":[{"type":"path","id":"rule","d":"M 20 280 L 300 280","stroke":"#e8e8f0","stroke_width":4.0,"progress":0.0}]}],"animations":[{"target":"rule","property":"progress","start":0,"duration":3000,"from":0.0,"to":1.0,"easing":"linear"}]})panel_scene";
